 // document. write("<p>今天天气不错</p>");
document .write("<p>我和我的剑到此一游</p>");
document .write("<p>但愿长醉不复醒</p>");
document .write("<p>你的血 让我诗兴大发</p>");
document .write("<p>十步杀一人，千里不留行</p>");
document .write("<p>努力有用的话 还要天才干什么</p>");
document .write("<p>一篇诗，一斗酒，一曲长歌，一剑天涯</p>");
document .write("<p>来干~ ~，来干~~</p>");
document .write("<p>今朝有酒今朝醉</p>");
document .write("<p>大河之间天上来</p>");
document .write("<p>来~干~</p>");
document .write("<p>邂逅你，是生生世世的宿命</p>");
document .write("<p>凤兮凤兮归故乡，遨游四海求其凰</p>");
document .write("<p>三尺常见，斩不断相思缠绕</p>");
document .write("<p>可以赶尽，但无法杀绝</p>");
document .write("<p>旅途无止境。</p>");
document .write("<p>时间也抹杀不了颜值</p>");
document .write("<p>别盯着我的脸走神了，你正在有效地害死队友</p>");
document .write("<p>青丘之民的灵魂不会永远漂泊，因为我在这里</p>");
document .write("<p>狐鸣风啸</p>");
document .write("<p>永恒于刹那间，只隔着我的剑</p>");
document .write("<p>醉里挑灯看剑</p>");
document .write("<p>一剑伤寒十四周</p>");
document .write("<p>并非幸存者，而是赢家</p>");
document .write("<p>死过一次，就没多余生命可浪费了</p>");
document .write("<p>是狐不是祸，最近就流行我这样高冷的主角</p>");
document .write("<p>身作泛舟，魂渡彼岸</p>");
document .write("<p>青丘之灵不灭</p>");
document .write("<p>狐死，必首丘</p>");

 
